type = "blog"
title = "Blog"
description = "Notes and updates."

[[posts]]
title = "HKUST IT Courses (Part I)"
date = "2026-02-09"
source = "blog/course1.md"
summary = "The course introduction of HKUST IT postgraduate program."
tags = ["hkust"]
