type = "blog"
title = "Blog"
description = "Notes and updates."

[[posts]]
title = "Welcome to my blog"
date = "2026-02-09"
source = "blog/welcome.md"
summary = "这是我的第一篇博客的 TL;DR 简短介绍。"
tags = ["intro"]
