type = "blog"
title = "Blog"
description = "Notes and updates."

[[posts]]
title = "Principle of Cybersecurity"
date = "2025-12-30"
source = "blog/Principle_of_Cybersecurity.md"
summary = "Review of CSIT 5730 Principle of Cybersecurity"
tags = ["cs"]
