[site]
title = "Nanjun Zhou"
description = "Master student at HKUST"
favicon = "/favicon.svg"
last_updated = "November 18, 2025"

[author]
name = "Nanjun Zhou"
title = "Master Student"
institution = "HKUST"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "arbiter0102@gmail.com"
location = "Hong Kong"
location_url = "https://maps.google.com"
location_details = [
  "3/F Annex, The Hong Kong University of Science and Technology",
  "Clear Water Bay, Kowloon, Hong Kong"
]
google_scholar = "https://scholar.google.com/citations?user=gtmR4jkAAAAJ&hl=en"
# orcid = "https://orcid.org"
github = "https://github.com/quantum-bitss"
linkedin = "https://www.linkedin.com/in/nanjun-zhou-703a08354/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

# [[navigation]]
# title = "Teaching"
# type = "page"
# target = "teaching"
# href = "/teaching"

# [[navigation]]
# title = "Awards"
# type = "page"
# target = "awards"
# href = "/awards"

# [[navigation]]
# title = "Services"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
