[[news]]
date = "2025-12"
content = "ðŸš€ðŸš€ BackdoorDM receives the Second-class Award in The 15th Guangdong-Hong Kong-Macao Conference on Image and Graphics!"

[[news]]
date = "2025-09"
content = "ðŸš€ðŸš€ BackdoorDM is accepted by NeurIPS 2025!"

[[news]]
date = "2025-08"
content = "I officially join Responsible AI group, ZJU as a research intern, focusing on Agent Security."

[[news]]
date = "2025-07"
content = "ðŸŽ“ðŸ“œ I graduate from SCUT."

[[news]]
date = "2025-02"
content = "Our latest work BackdoorDM on Diffusion Backdoor is released!"

